/**
 * Session-key types and helpers.
 *
 * A Session is a scoped, time-bounded delegation from a wallet's admin
 * signer to another key. The session key is enforced on-chain by the
 * Altana account contract: calls outside the granted permissions revert
 * at validation time. Revocation is a single tx; effect is immediate.
 *
 * Permission types mirror Porto's schema (signature-scheme agnostic).
 */

import type { Address, Hex } from "viem";
import type { Signer } from "./signer.js";

/** A single allowed call rule. AND semantics between the optional fields. */
export type CallPermission =
  | { signature: string; to: Address }
  | { signature: string }
  | { to: Address };

/** A spending cap for a token over a rolling period. */
export type SpendPermission = {
  limit: bigint;
  period: "minute" | "hour" | "day" | "week" | "month" | "year";
  /** Omit for native token (ETH). */
  token?: Address;
};

export type SessionPermissions = {
  /** Allowed calls. If omitted, all targets are allowed (use carefully). */
  calls?: readonly CallPermission[];
  /** Per-token spending caps. */
  spend?: readonly SpendPermission[];
};

/**
 * A live session — the result of grantSession. Carries everything an agent
 * needs to act on the wallet within the granted scope.
 *
 * The integrator hands this object to whichever process runs the agent;
 * the agent uses it with execute(session, calls).
 */
export type Session = {
  /** The wallet this session can act on. */
  walletAddress: Address;
  /** The session key's signer. Agent signs with this. */
  signer: Signer;
  /** Public key registered on-chain. Identifier for revocation. */
  publicKey: Hex;
  /** Granted permissions (also enforced on-chain). */
  permissions: SessionPermissions;
  /** Unix epoch seconds when this session expires. */
  expiry: number;
};

/**
 * What grantSession returns: the live Session, plus provenance for the grant
 * itself.
 *
 * The hash is not on Session because a Session outlives the transaction that
 * created it. Integrators persist it, hand it to an agent process, and pass it
 * to execute() for days afterwards. A transaction hash sitting on it that long
 * describes something that already happened, so it belongs to the grant's
 * result, not to the session.
 *
 * Assignable to Session, so every existing caller keeps working unchanged.
 */
export type GrantSessionResult = Session & {
  /**
   * The transaction that carried the grant, when the relay reported one.
   * Optional: the relay can confirm an intent without surfacing a receipt.
   */
  transactionHash?: Hex;
  /**
   * Present only for a gated-L2 grant: the extra L2 wiring the SDK performed
   * (gate binding + optional proof bridge). Absent for full-stack chains.
   */
  l2?: {
    chainId: number;
    keyHash: Hex;
    keyId: Hex;
    wireTxHash?: Hex;
    cached?: boolean;
  };
};

/** Options for grantSession. */
export type GrantSessionOptions = {
  permissions: SessionPermissions;
  /** Unix epoch seconds. Most apps use Date.now()/1000 + N. */
  expiry: number;
  /**
   * Provide your own session signer (e.g., generated by your backend and
   * stored alongside user state). If omitted, the SDK generates a fresh
   * secp256k1 session signer and returns it as part of the Session.
   */
  sessionSigner?: Signer;
  /**
   * Register the session's public key in the KeyStore registry (default
   * true). Registration is what lets any third party verify the key's
   * authority on-chain. Pass false for an ephemeral, account-only session —
   * it works identically (permissions/expiry enforced by the account) but is
   * invisible to KeyStore readers such as `verify_authorization`; it can be
   * registered later with `registerSessionKey`.
   */
  register?: boolean;
};
