/**
 * Session-key types and helpers.
 *
 * A Session is a scoped, time-bounded delegation from a wallet's admin
 * signer to another key. The session key is enforced on-chain by the
 * Altana account contract: calls outside the granted permissions revert
 * at validation time. Revocation is a single tx; effect is immediate.
 *
 * Permission types mirror Porto's schema (signature-scheme agnostic).
 */

import type { Address, Hex } from "viem";
import type { Signer } from "./signer.js";

/** A single allowed call rule. AND semantics between the optional fields. */
export type CallPermission =
  | { signature: string; to: Address }
  | { signature: string }
  | { to: Address };

/** A spending cap for a token over a rolling period. */
export type SpendPermission = {
  limit: bigint;
  period: "minute" | "hour" | "day" | "week" | "month" | "year";
  /** Omit for native token (ETH). */
  token?: Address;
};

export type SessionPermissions = {
  /** Allowed calls. If omitted, all targets are allowed (use carefully). */
  calls?: readonly CallPermission[];
  /** Per-token spending caps. */
  spend?: readonly SpendPermission[];
};

/**
 * A live session — the result of grantSession. Carries everything an agent
 * needs to act on the wallet within the granted scope.
 *
 * The integrator hands this object to whichever process runs the agent;
 * the agent uses it with execute(session, calls).
 */
export type Session = {
  /** The wallet this session can act on. */
  walletAddress: Address;
  /** The session key's signer. Agent signs with this. */
  signer: Signer;
  /** Public key registered on-chain. Identifier for revocation. */
  publicKey: Hex;
  /** Granted permissions (also enforced on-chain). */
  permissions: SessionPermissions;
  /** Unix epoch seconds when this session expires. */
  expiry: number;
};

/** Options for grantSession. */
export type GrantSessionOptions = {
  permissions: SessionPermissions;
  /** Unix epoch seconds. Most apps use Date.now()/1000 + N. */
  expiry: number;
  /**
   * Provide your own session signer (e.g., generated by your backend and
   * stored alongside user state). If omitted, the SDK generates a fresh
   * secp256k1 session signer and returns it as part of the Session.
   */
  sessionSigner?: Signer;
};
