/**
 * Session-key types and helpers.
 *
 * A Session is a scoped, time-bounded delegation from a wallet's admin
 * signer to another key. The session key is enforced on-chain by the
 * Altana account contract: calls outside the granted permissions revert
 * at validation time. Revocation is a single tx; effect is immediate.
 *
 * Permission types mirror Porto's schema (signature-scheme agnostic).
 */

import type { Address, Hex } from "viem";
import type { Signer } from "./signer.js";

/** A single allowed call rule. AND semantics between the optional fields. */
export type CallPermission =
  | { signature: string; to: Address }
  | { signature: string }
  | { to: Address };

/** A spending cap for a token over a rolling period. */
export type SpendPermission = {
  limit: bigint;
  period: "minute" | "hour" | "day" | "week" | "month" | "year";
  /** Omit for native token (ETH). */
  token?: Address;
};

export type SessionPermissions = {
  /** Allowed calls. If omitted, all targets are allowed (use carefully). */
  calls?: readonly CallPermission[];
  /** Per-token spending caps. */
  spend?: readonly SpendPermission[];
};

/**
 * A live session — the result of grantSession. Carries everything an agent
 * needs to act on the wallet within the granted scope.
 *
 * The integrator hands this object to whichever process runs the agent;
 * the agent uses it with execute(session, calls).
 */
export type Session = {
  /** The wallet this session can act on. */
  walletAddress: Address;
  /** The session key's signer. Agent signs with this. */
  signer: Signer;
  /** Public key registered on-chain. Identifier for revocation. */
  publicKey: Hex;
  /** Granted permissions (also enforced on-chain). */
  permissions: SessionPermissions;
  /** Unix epoch seconds when this session expires. */
  expiry: number;
};

/**
 * What grantSession returns: the live Session, plus provenance for the grant
 * itself.
 *
 * The hash is not on Session because a Session outlives the transaction that
 * created it. Integrators persist it, hand it to an agent process, and pass it
 * to execute() for days afterwards. A transaction hash sitting on it that long
 * describes something that already happened, so it belongs to the grant's
 * result, not to the session.
 *
 * Assignable to Session, so every existing caller keeps working unchanged.
 */
export type GrantSessionResult = Session & {
  /**
   * The transaction that carried the grant, when the relay reported one.
   * Optional: the relay can confirm an intent without surfacing a receipt.
   */
  transactionHash?: Hex;
};

/** Options for grantSession. */
export type GrantSessionOptions = {
  permissions: SessionPermissions;
  /** Unix epoch seconds. Most apps use Date.now()/1000 + N. */
  expiry: number;
  /**
   * Provide your own session signer (e.g., generated by your backend and
   * stored alongside user state). If omitted, the SDK generates a fresh
   * secp256k1 session signer and returns it as part of the Session —
   * but that key exists ONLY in this process's memory. If the process
   * exits before you persist it, the granted on-chain authorization is
   * permanently unusable (revoke-and-regrant is the only exit). Prefer
   * generating your own key, storing it in a secret store, and passing
   * `signerFromPrivateKey(key)` here; persist the rest of the session
   * with `serializeSession`.
   */
  sessionSigner?: Signer;
  /**
   * Register the session's public key in the KeyStore registry (default
   * true). Registration is what lets any third party verify the key's
   * authority on-chain. Pass false for an ephemeral, account-only session —
   * it works identically (permissions/expiry enforced by the account) but is
   * invisible to KeyStore readers such as `verify_authorization`; it can be
   * registered later with `registerSessionKey`.
   */
  register?: boolean;
};

/**
 * The JSON-safe half of a Session: everything except the secret.
 *
 * `serializeSession` produces this; store it anywhere (a file, a database,
 * localStorage). The session key itself is the caller's to keep — generate
 * it yourself, store it in a secret store, and rebuild the signer at load
 * time. `deserializeSession` marries the two halves back together.
 *
 * `limit` is a decimal string because JSON has no bigint. Unknown extra
 * fields on a stored object are ignored, so callers can wrap this in their
 * own envelope (add names, timestamps, a version field) without friction.
 */
export type SerializedCallPermission =
  | { signature: string; to: Address }
  | { signature: string }
  | { to: Address };

export type SerializedSession = {
  walletAddress: Address;
  publicKey: Hex;
  permissions: {
    calls?: readonly SerializedCallPermission[];
    /** `limit` as a decimal string — JSON has no bigint. */
    spend?: readonly { limit: string; period: SpendPermission["period"]; token?: Address }[];
  };
  expiry: number;
};

/**
 * The safe way to persist a Session: returns a plain JSON-safe object with
 * NO key material in it. Field-by-field on purpose — a GrantSessionResult's
 * transactionHash (and anything else riding on the object) is dropped.
 */
export function serializeSession(session: Session): SerializedSession {
  const { permissions } = session;
  return {
    walletAddress: session.walletAddress,
    publicKey: session.publicKey,
    permissions: {
      ...(permissions.calls ? { calls: permissions.calls.map((c) => ({ ...c })) } : {}),
      ...(permissions.spend
        ? {
            spend: permissions.spend.map((s) => ({
              limit: s.limit.toString(),
              period: s.period,
              ...(s.token ? { token: s.token } : {}),
            })),
          }
        : {}),
    },
    expiry: session.expiry,
  };
}

/**
 * Rebuilds a live Session from its stored half plus the session signer the
 * caller kept (e.g. `signerFromPrivateKey(keyFromYourSecretStore)`).
 *
 * Refuses a signer that does not match the stored `publicKey`: signing with
 * the wrong key would not fail here, it would fail later as an opaque relay
 * rejection. The rebuilt session's `publicKey` is taken from the signer
 * (canonical casing), so a storage layer that re-cased the hex cannot
 * change the on-chain key hash.
 */
export function deserializeSession(stored: SerializedSession, signer: Signer): Session {
  if (signer.publicKey.toLowerCase() !== stored.publicKey.toLowerCase()) {
    throw new Error(
      `deserializeSession: the supplied signer's public key (${signer.publicKey}) does not ` +
        `match the stored session's (${stored.publicKey}). This session was granted to a ` +
        `different key — restore the key that was used at grantSession time.`,
    );
  }
  const spend = stored.permissions.spend?.map((s) => {
    if (!/^\d+$/.test(s.limit)) {
      throw new Error(
        `deserializeSession: permissions.spend limit ${JSON.stringify(s.limit)} is not a ` +
          `decimal string. Limits are serialized as decimal strings (bigint.toString()).`,
      );
    }
    return { limit: BigInt(s.limit), period: s.period, ...(s.token ? { token: s.token } : {}) };
  });
  return {
    walletAddress: stored.walletAddress,
    signer,
    publicKey: signer.publicKey,
    permissions: {
      ...(stored.permissions.calls ? { calls: stored.permissions.calls.map((c) => ({ ...c })) } : {}),
      ...(spend ? { spend } : {}),
    },
    expiry: stored.expiry,
  };
}
