#!/usr/bin/env node
/**
 * Writes the build stamp a package reports at runtime.
 *
 * A consumer resolves this package through `dist`, which is gitignored, so
 * nothing about the artifact that actually runs is recorded anywhere. On
 * 2026-10-07 the only way to establish which SDK a live spine run had executed
 * was to recognise a distinctive sentence in one of its error messages — a
 * method that fails for any fix whose message is a shared string, and which
 * produced one wrong report before it produced a right one.
 *
 * So the build records it. `commit` is the source the artifact was built from
 * and `dirty` says whether the tree had uncommitted changes, because "built
 * from 92ba3e9" is a different claim from "built from 92ba3e9 plus edits" and
 * only the second one explains a surprise.
 *
 * Generated into src/ rather than dist/ so `bun test` and a direct source
 * import see the same value a built consumer does. It is gitignored: a
 * committed stamp would be stale for every build but the one that wrote it,
 * which is the failure this exists to prevent.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function git(args) {
  try {
    return execFileSync("git", args, { cwd: root, encoding: "utf8" }).trim();
  } catch {
    // A published tarball or an export has no repository. Unknown is honest;
    // guessing a commit here would be the exact error this file prevents.
    return "";
  }
}

const commit = git(["rev-parse", "HEAD"]);
const dirty = git(["status", "--porcelain"]).length > 0;
const target = process.argv[2];
if (!target) {
  console.error("usage: stamp-build.mjs <path to buildStamp.ts>");
  process.exit(2);
}

writeFileSync(
  join(root, target),
  `// Generated by scripts/stamp-build.mjs. Not committed: see that file.
/** The source commit this build was produced from; empty when built outside a repository. */
export const BUILD_COMMIT = ${JSON.stringify(commit)};
/** Whether the tree had uncommitted changes when this build ran. */
export const BUILD_DIRTY = ${JSON.stringify(dirty)};
/** When this build ran, ISO 8601. */
export const BUILT_AT = ${JSON.stringify(new Date().toISOString())};
`,
);
console.log(`stamped ${target}: ${commit || "(no repository)"}${dirty ? " +dirty" : ""}`);
